/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QrPrintRouteImport } from './routes/qr-print'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as LifecycleRouteImport } from './routes/lifecycle'
import { Route as ImportRouteImport } from './routes/import'
import { Route as EdcRouteImport } from './routes/edc'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ConsumablesRouteImport } from './routes/consumables'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as ItemsIndexRouteImport } from './routes/items.index'
import { Route as ItemsItemIdRouteImport } from './routes/items.$itemId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QrPrintRoute = QrPrintRouteImport.update({
  id: '/qr-print',
  path: '/qr-print',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleRoute = LifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const EdcRoute = EdcRouteImport.update({
  id: '/edc',
  path: '/edc',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumablesRoute = ConsumablesRouteImport.update({
  id: '/consumables',
  path: '/consumables',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/consumables': typeof ConsumablesRoute
  '/credentials': typeof CredentialsRoute
  '/edc': typeof EdcRoute
  '/import': typeof ImportRoute
  '/lifecycle': typeof LifecycleRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/qr-print': typeof QrPrintRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/items/': typeof ItemsIndexRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/consumables': typeof ConsumablesRoute
  '/credentials': typeof CredentialsRoute
  '/edc': typeof EdcRoute
  '/import': typeof ImportRoute
  '/lifecycle': typeof LifecycleRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/qr-print': typeof QrPrintRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/items': typeof ItemsIndexRoute
  '/locations': typeof LocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/consumables': typeof ConsumablesRoute
  '/credentials': typeof CredentialsRoute
  '/edc': typeof EdcRoute
  '/import': typeof ImportRoute
  '/lifecycle': typeof LifecycleRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/qr-print': typeof QrPrintRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/items/': typeof ItemsIndexRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/consumables'
    | '/credentials'
    | '/edc'
    | '/import'
    | '/lifecycle'
    | '/loans'
    | '/login'
    | '/operations'
    | '/qr-print'
    | '/search'
    | '/setup'
    | '/items/$itemId'
    | '/items/'
    | '/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/consumables'
    | '/credentials'
    | '/edc'
    | '/import'
    | '/lifecycle'
    | '/loans'
    | '/login'
    | '/operations'
    | '/qr-print'
    | '/search'
    | '/setup'
    | '/items/$itemId'
    | '/items'
    | '/locations'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/consumables'
    | '/credentials'
    | '/edc'
    | '/import'
    | '/lifecycle'
    | '/loans'
    | '/login'
    | '/operations'
    | '/qr-print'
    | '/search'
    | '/setup'
    | '/items/$itemId'
    | '/items/'
    | '/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  ConsumablesRoute: typeof ConsumablesRoute
  CredentialsRoute: typeof CredentialsRoute
  EdcRoute: typeof EdcRoute
  ImportRoute: typeof ImportRoute
  LifecycleRoute: typeof LifecycleRoute
  LoansRoute: typeof LoansRoute
  LoginRoute: typeof LoginRoute
  OperationsRoute: typeof OperationsRoute
  QrPrintRoute: typeof QrPrintRoute
  SearchRoute: typeof SearchRoute
  SetupRoute: typeof SetupRoute
  ItemsItemIdRoute: typeof ItemsItemIdRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-print': {
      id: '/qr-print'
      path: '/qr-print'
      fullPath: '/qr-print'
      preLoaderRoute: typeof QrPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle': {
      id: '/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof LifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edc': {
      id: '/edc'
      path: '/edc'
      fullPath: '/edc'
      preLoaderRoute: typeof EdcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumables': {
      id: '/consumables'
      path: '/consumables'
      fullPath: '/consumables'
      preLoaderRoute: typeof ConsumablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId': {
      id: '/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  ConsumablesRoute: ConsumablesRoute,
  CredentialsRoute: CredentialsRoute,
  EdcRoute: EdcRoute,
  ImportRoute: ImportRoute,
  LifecycleRoute: LifecycleRoute,
  LoansRoute: LoansRoute,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRoute,
  QrPrintRoute: QrPrintRoute,
  SearchRoute: SearchRoute,
  SetupRoute: SetupRoute,
  ItemsItemIdRoute: ItemsItemIdRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
