/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirtualAssetsRouteImport } from './routes/virtual-assets'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QrPrintRouteImport } from './routes/qr-print'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationScanRouteImport } from './routes/location-scan'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as ImportRouteImport } from './routes/import'
import { Route as EdcRouteImport } from './routes/edc'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ConsumablesRouteImport } from './routes/consumables'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AbnormalRouteImport } from './routes/abnormal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags.index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as ItemsItemIdRouteImport } from './routes/items.$itemId'

const VirtualAssetsRoute = VirtualAssetsRouteImport.update({
  id: '/virtual-assets',
  path: '/virtual-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QrPrintRoute = QrPrintRouteImport.update({
  id: '/qr-print',
  path: '/qr-print',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationScanRoute = LocationScanRouteImport.update({
  id: '/location-scan',
  path: '/location-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const EdcRoute = EdcRouteImport.update({
  id: '/edc',
  path: '/edc',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumablesRoute = ConsumablesRouteImport.update({
  id: '/consumables',
  path: '/consumables',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AbnormalRoute = AbnormalRouteImport.update({
  id: '/abnormal',
  path: '/abnormal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abnormal': typeof AbnormalRoute
  '/assets': typeof AssetsRoute
  '/capture': typeof CaptureRoute
  '/consumables': typeof ConsumablesRoute
  '/credentials': typeof CredentialsRoute
  '/edc': typeof EdcRoute
  '/import': typeof ImportRoute
  '/loans': typeof LoansRoute
  '/location-scan': typeof LocationScanRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/qr-print': typeof QrPrintRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/virtual-assets': typeof VirtualAssetsRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/locations/': typeof LocationsIndexRoute
  '/tags/': typeof TagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abnormal': typeof AbnormalRoute
  '/assets': typeof AssetsRoute
  '/capture': typeof CaptureRoute
  '/consumables': typeof ConsumablesRoute
  '/credentials': typeof CredentialsRoute
  '/edc': typeof EdcRoute
  '/import': typeof ImportRoute
  '/loans': typeof LoansRoute
  '/location-scan': typeof LocationScanRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/qr-print': typeof QrPrintRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/virtual-assets': typeof VirtualAssetsRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/locations': typeof LocationsIndexRoute
  '/tags': typeof TagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abnormal': typeof AbnormalRoute
  '/assets': typeof AssetsRoute
  '/capture': typeof CaptureRoute
  '/consumables': typeof ConsumablesRoute
  '/credentials': typeof CredentialsRoute
  '/edc': typeof EdcRoute
  '/import': typeof ImportRoute
  '/loans': typeof LoansRoute
  '/location-scan': typeof LocationScanRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/qr-print': typeof QrPrintRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/virtual-assets': typeof VirtualAssetsRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/locations/': typeof LocationsIndexRoute
  '/tags/': typeof TagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abnormal'
    | '/assets'
    | '/capture'
    | '/consumables'
    | '/credentials'
    | '/edc'
    | '/import'
    | '/loans'
    | '/location-scan'
    | '/login'
    | '/operations'
    | '/qr-print'
    | '/search'
    | '/settings'
    | '/setup'
    | '/virtual-assets'
    | '/items/$itemId'
    | '/locations/'
    | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abnormal'
    | '/assets'
    | '/capture'
    | '/consumables'
    | '/credentials'
    | '/edc'
    | '/import'
    | '/loans'
    | '/location-scan'
    | '/login'
    | '/operations'
    | '/qr-print'
    | '/search'
    | '/settings'
    | '/setup'
    | '/virtual-assets'
    | '/items/$itemId'
    | '/locations'
    | '/tags'
  id:
    | '__root__'
    | '/'
    | '/abnormal'
    | '/assets'
    | '/capture'
    | '/consumables'
    | '/credentials'
    | '/edc'
    | '/import'
    | '/loans'
    | '/location-scan'
    | '/login'
    | '/operations'
    | '/qr-print'
    | '/search'
    | '/settings'
    | '/setup'
    | '/virtual-assets'
    | '/items/$itemId'
    | '/locations/'
    | '/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbnormalRoute: typeof AbnormalRoute
  AssetsRoute: typeof AssetsRoute
  CaptureRoute: typeof CaptureRoute
  ConsumablesRoute: typeof ConsumablesRoute
  CredentialsRoute: typeof CredentialsRoute
  EdcRoute: typeof EdcRoute
  ImportRoute: typeof ImportRoute
  LoansRoute: typeof LoansRoute
  LocationScanRoute: typeof LocationScanRoute
  LoginRoute: typeof LoginRoute
  OperationsRoute: typeof OperationsRoute
  QrPrintRoute: typeof QrPrintRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  VirtualAssetsRoute: typeof VirtualAssetsRoute
  ItemsItemIdRoute: typeof ItemsItemIdRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virtual-assets': {
      id: '/virtual-assets'
      path: '/virtual-assets'
      fullPath: '/virtual-assets'
      preLoaderRoute: typeof VirtualAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-print': {
      id: '/qr-print'
      path: '/qr-print'
      fullPath: '/qr-print'
      preLoaderRoute: typeof QrPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-scan': {
      id: '/location-scan'
      path: '/location-scan'
      fullPath: '/location-scan'
      preLoaderRoute: typeof LocationScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edc': {
      id: '/edc'
      path: '/edc'
      fullPath: '/edc'
      preLoaderRoute: typeof EdcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumables': {
      id: '/consumables'
      path: '/consumables'
      fullPath: '/consumables'
      preLoaderRoute: typeof ConsumablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abnormal': {
      id: '/abnormal'
      path: '/abnormal'
      fullPath: '/abnormal'
      preLoaderRoute: typeof AbnormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId': {
      id: '/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbnormalRoute: AbnormalRoute,
  AssetsRoute: AssetsRoute,
  CaptureRoute: CaptureRoute,
  ConsumablesRoute: ConsumablesRoute,
  CredentialsRoute: CredentialsRoute,
  EdcRoute: EdcRoute,
  ImportRoute: ImportRoute,
  LoansRoute: LoansRoute,
  LocationScanRoute: LocationScanRoute,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRoute,
  QrPrintRoute: QrPrintRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  VirtualAssetsRoute: VirtualAssetsRoute,
  ItemsItemIdRoute: ItemsItemIdRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
